package com.wut.car.model;

import java.io.Serializable;

/**
 * News 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class News implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** time. */
	private Integer time;

	/** biamhao. */
	private Integer biamhao;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public News() {
	}

	/**
	 * time 傪愝掕偟傑偡.
	 * 
	 * @param time
	 *            time
	 */
	public void setTime(Integer time) {
		this.time = time;
	}

	/**
	 * time 傪庢摼偟傑偡.
	 * 
	 * @return time
	 */
	public Integer getTime() {
		return this.time;
	}

	/**
	 * biamhao 傪愝掕偟傑偡.
	 * 
	 * @param biamhao
	 *            biamhao
	 */
	public void setBiamhao(Integer biamhao) {
		this.biamhao = biamhao;
	}

	/**
	 * biamhao 傪庢摼偟傑偡.
	 * 
	 * @return biamhao
	 */
	public Integer getBiamhao() {
		return this.biamhao;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((time == null) ? 0 : time.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		News other = (News) obj;
		if (time == null) {
			if (other.time != null) {
				return false;
			}
		} else if (!time.equals(other.time)) {
			return false;
		}

		return true;
	}

}
