package com.wut.car.model;

import java.io.Serializable;

/**
 * user 儌僨儖僋儔僗.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class User implements Serializable {

	/** serialVersionUID. */
	private static final long serialVersionUID = 1L;

	/** username. */
	private String username;

	/** sex. */
	private Integer sex;

	/** nianji. */
	private Integer nianji;

	/**
	 * 僐儞僗僩儔僋僞.
	 */
	public User() {
	}

	/**
	 * username 傪愝掕偟傑偡.
	 * 
	 * @param username
	 *            username
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * username 傪庢摼偟傑偡.
	 * 
	 * @return username
	 */
	public String getUsername() {
		return this.username;
	}

	/**
	 * sex 傪愝掕偟傑偡.
	 * 
	 * @param sex
	 *            sex
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * sex 傪庢摼偟傑偡.
	 * 
	 * @return sex
	 */
	public Integer getSex() {
		return this.sex;
	}

	/**
	 * nianji 傪愝掕偟傑偡.
	 * 
	 * @param nianji
	 *            nianji
	 */
	public void setNianji(Integer nianji) {
		this.nianji = nianji;
	}

	/**
	 * nianji 傪庢摼偟傑偡.
	 * 
	 * @return nianji
	 */
	public Integer getNianji() {
		return this.nianji;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((username == null) ? 0 : username.hashCode());

		return result;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}
		if (obj == null) {
			return false;
		}
		if (getClass() != obj.getClass()) {
			return false;
		}
		User other = (User) obj;
		if (username == null) {
			if (other.username != null) {
				return false;
			}
		} else if (!username.equals(other.username)) {
			return false;
		}

		return true;
	}

}
